---
Name: betternavigator
After: 'framework/*','cms/*'
---
LeftAndMain:
  extra_requirements_javascript:
    - 'betternavigator/javascript/BN.LeftAndMain.Preview.js'
ContentController:
  extensions:
    - BetterNavigatorExtension
